"use client";

import { useMemo, useState } from "react";
import type { Metadata } from "next";

type Game = { name: string; native: string; country: string; region: string; mechanism: string; time: string; players: string; difficulty: string; accent: string; blurb: string };
const games: Game[] = [
  { name: "Scopa", native: "Scopa", country: "意大利", region: "欧洲", mechanism: "捕鱼与抓牌", time: "15–30 分钟", players: "2–4 人", difficulty: "入门", accent: "coral", blurb: "用一张牌捕获桌面上相加等于它的牌，收走最多牌的人获胜。" },
  { name: "Briscola", native: "Briscola", country: "意大利", region: "欧洲", mechanism: "墩牌", time: "20 分钟", players: "2–4 人", difficulty: "入门", accent: "gold", blurb: "翻开一张王牌，判断时机，赢下分值最高的墩。" },
  { name: "Durak", native: "Дурак", country: "俄罗斯", region: "东欧", mechanism: "攻防与脱手", time: "20–40 分钟", players: "2–6 人", difficulty: "中等", accent: "blue", blurb: "轮流进攻与防守，最后手里还留着牌的人成为 Durak。" },
  { name: "Tiến Lên", native: "Tiến Lên", country: "越南", region: "东南亚", mechanism: "爬梯与脱手", time: "15–25 分钟", players: "2–4 人", difficulty: "中等", accent: "violet", blurb: "用更大的同型牌压过上家，先出完手牌。" },
  { name: "Koi-Koi", native: "こいこい", country: "日本", region: "东亚", mechanism: "配对与组合", time: "10–20 分钟", players: "2 人", difficulty: "中等", accent: "rose", blurb: "以花札组成役，见好就收，或选择继续挑战更高分。" },
  { name: "Go-Stop", native: "고스톱", country: "韩国", region: "东亚", mechanism: "抓分", time: "20–40 分钟", players: "2–3 人", difficulty: "中等", accent: "mint", blurb: "收集同月花牌组成牌型，在 Stop 与 Go 之间做决定。" },
];

export default function Home() {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("全部"); const [active, setActive] = useState<Game | null>(null); const [playing, setPlaying] = useState(false); const [score, setScore] = useState(0); const [selected, setSelected] = useState<number | null>(null);
  const filtered = useMemo(() => games.filter(g => (filter === "全部" || g.region === filter) && `${g.name}${g.country}${g.mechanism}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  return <main>
    <nav className="nav"><div className="brand"><span className="brand-mark">✦</span> WORLD CARD <small>ATLAS</small></div><div className="nav-links"><a href="#explore">探索</a><a href="#library">游戏库</a><a href="#learn">学习中心</a></div><button className="lang">中 / EN⌄</button><button className="menu">☰</button></nav>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">A LIVING ARCHIVE OF PLAY</p><h1>一张牌，<em>一段世界。</em></h1><p className="lead">探索全球纸牌文化，理解它们的故事，<br/>然后坐下来——立即开始玩。</p><div className="hero-actions"><button className="btn primary" onClick={() => document.getElementById("explore")?.scrollIntoView({ behavior: "smooth" })}>探索世界 <span>↗</span></button><button className="btn ghost" onClick={() => { setPlaying(true); document.getElementById("play")?.scrollIntoView({ behavior: "smooth" }); }}>立即试玩 <span>▶</span></button></div><div className="hero-note"><span>◉</span> 今日焦点 · <b>意大利 Scopa</b><small> 15 分钟入门</small></div></div><div className="hero-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-card card-back">✦</div><div className="hero-card card-front"><span>♠</span><strong>A</strong><i>♠</i></div><span className="art-caption">CARDS CARRY<br/>CULTURE</span></div></section>
    <section id="explore" className="section explore"><div className="section-head"><div><p className="eyebrow">01 · DISCOVER BY PLACE</p><h2>从地图开始探索</h2></div><a className="text-link" href="#library">查看全部国家 →</a></div><div className="map-panel"><div className="world-map"><span className="map-dot d1">意大利</span><span className="map-dot d2">俄罗斯</span><span className="map-dot d3">日本</span><span className="map-dot d4">越南</span><div className="continents">✦</div><div className="map-label">THE WORLD<br/><b>IS YOUR TABLE</b></div></div><div className="place-list"><div className="place-title">精选地区 <span>EXPLORE</span></div>{[["意大利","4 个游戏","🇮🇹"],["日本","8 个游戏","🇯🇵"],["东南亚","12 个游戏","🌏"],["东欧","6 个游戏","🇷🇺"]].map((p,i)=><button key={p[0]} className={`place ${i===0?"chosen":""}`} onClick={() => setFilter(i===0?"欧洲":i===1||i===2?"东亚":"东欧")}><span>{p[2]}</span><b>{p[0]}</b><small>{p[1]}</small><i>↗</i></button>)}</div></div></section>
    <section id="library" className="section library"><div className="section-head"><div><p className="eyebrow">02 · FIND YOUR NEXT GAME</p><h2>游戏档案库</h2></div><div className="controls"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索游戏、国家或机制…"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>全部</option><option>欧洲</option><option>东亚</option><option>东欧</option><option>东南亚</option></select></div></div><div className="game-grid">{filtered.map(g=><article className="game-card" key={g.name} onClick={()=>setActive(g)}><div className={`game-art ${g.accent}`}><span>{g.native}</span><strong>{g.name[0]}</strong><i>✦</i></div><div className="game-info"><div className="game-top"><span>{g.country}</span><span>{g.mechanism}</span></div><h3>{g.name}</h3><p>{g.blurb}</p><div className="meta"><span>◷ {g.time}</span><span>♧ {g.players}</span><b>{g.difficulty}</b></div></div></article>)}</div></section>
    <section id="play" className="play-section"><div className="play-intro"><p className="eyebrow">03 · LEARN BY PLAYING</p><h2>三分钟，<br/><em>学会 Scopa。</em></h2><p>别读规则书。跟着桌面上的提示走一步，就能理解这款意大利经典捕鱼牌戏。</p><button className="btn primary" onClick={()=>setPlaying(true)}>{playing?"教学进行中":"开始互动教学"} <span>↗</span></button></div><div className="table"><div className="table-top"><span>SCOPA · 新手桌</span><span>第 1 / 3 步</span></div><div className="instruction">{selected===null?"从手牌中选择一张牌":selected===0?"很好！A 可以捕获桌面上的 A。":"试试发光的牌"}<small>目标：捕获桌面上的牌，拿到最多分数。</small></div><div className="table-cards center"><div className="playing-card mini red">A</div><div className="playing-card mini">7</div><div className="playing-card mini">4</div></div><div className="table-cards hand">{["A","5","7"].map((x,i)=><button key={x} className={`playing-card ${i===0||i===2?"glow":""} ${selected===i?"picked":""}`} onClick={()=>{setSelected(i); if(i===0)setScore(score+1)}}>{x}<small>♠</small></button>)}</div><div className="table-bottom"><span>你的得分 <b>{score}</b></span><span>AI · 意大利奶奶 🤖</span></div></div></section>
    <footer><div className="brand"><span className="brand-mark">✦</span> WORLD CARD <small>ATLAS</small></div><p>探索世界纸牌文化，并立即开始游玩。</p><span>© 2026 World Card Atlas</span></footer>
    {active&&<div className="modal-bg" onClick={()=>setActive(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button><div className={`modal-art game-art ${active.accent}`}><span>{active.native}</span><strong>{active.name[0]}</strong></div><p className="eyebrow">{active.country} · {active.mechanism}</p><h2>{active.name}</h2><p>{active.blurb}</p><div className="modal-meta"><span>{active.time}</span><span>{active.players}</span><span>{active.difficulty}</span></div><button className="btn primary" onClick={()=>{setActive(null);setPlaying(true);document.getElementById("play")?.scrollIntoView({behavior:"smooth"})}}>立即试玩 ↗</button></div></div>}
  </main>;
}
