/* eslint-disable @next/next/no-html-link-for-pages, jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex, jsx-a11y/click-events-have-key-events */
"use client";
import { useMemo, useState } from "react";
import { countries, games, mechanisms, regions, type Game } from "../lib/content";

export default function Home() {
  const [query, setQuery] = useState(""); const [region, setRegion] = useState("all"); const [mechanism, setMechanism] = useState("all"); const [active, setActive] = useState<Game | null>(null);
  const filtered = useMemo(() => games.filter((g) => (region === "all" || g.regionSlugs.includes(region)) && (mechanism === "all" || g.mechanismSlugs.includes(mechanism)) && `${g.name}${g.nativeName}${g.blurb}`.toLowerCase().includes(query.toLowerCase())), [query, region, mechanism]);
  return <main>
    <nav className="nav"><a className="brand" href="/"><span className="brand-mark">✦</span> WORLD CARD <small>ATLAS</small></a><div className="nav-links"><a href="#explore">探索</a><a href="#library">游戏库</a><a href="#learn">学习中心</a></div><span className="lang" aria-label="当前语言：中文">中</span><button className="menu" aria-label="打开菜单">☰</button></nav>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">A LIVING ARCHIVE OF PLAY</p><h1>一张牌，<em>一段世界。</em></h1><p className="lead">探索全球纸牌文化，理解它们的故事，<br />然后坐下来——立即开始玩。</p><div className="hero-actions"><button className="btn primary" onClick={() => document.getElementById("explore")?.scrollIntoView({ behavior: "smooth" })}>探索世界 <span>↗</span></button><a className="btn ghost" href="/games/scopa/play">立即试玩 <span>▶</span></a></div><div className="hero-note"><span>◉</span> 今日焦点 · <b>意大利 Scopa</b><small> 15 分钟入门</small></div></div><div className="hero-art"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="hero-card card-back">✦</div><div className="hero-card card-front"><span>♠</span><strong>A</strong><i>♠</i></div><span className="art-caption">CARDS CARRY<br />CULTURE</span></div></section>
    <section id="explore" className="section explore"><div className="section-head"><div><p className="eyebrow">01 · DISCOVER BY PLACE</p><h2>从地图开始探索</h2></div><a className="text-link" href="#library">查看全部游戏 →</a></div><div className="map-panel"><div className="world-map"><span className="map-dot d1">意大利</span><span className="map-dot d2">俄罗斯</span><span className="map-dot d3">日本</span><span className="map-dot d4">越南</span><div className="continents">✦</div><div className="map-label">THE WORLD<br /><b>IS YOUR TABLE</b></div></div><div className="place-list"><div className="place-title">精选地区 <span>EXPLORE</span></div>{countries.map((country) => <a key={country.slug} className="place" href={`/countries/${country.slug}`}><span>{country.flag}</span><b>{country.name}</b><small>{country.status === "published" ? `${country.gameSlugs.length} 个游戏` : "整理中"}</small><i>↗</i></a>)}</div></div></section>
    <section id="library" className="section library"><div className="section-head"><div><p className="eyebrow">02 · FIND YOUR NEXT GAME</p><h2>游戏档案库</h2></div><div className="controls"><label className="sr-only" htmlFor="game-search">搜索游戏、国家或机制</label><input id="game-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索游戏、国家或机制…" /><label className="sr-only" htmlFor="region-filter">按地区筛选</label><select id="region-filter" value={region} onChange={(e) => setRegion(e.target.value)}><option value="all">全部地区</option>{regions.map((r) => <option key={r.slug} value={r.slug}>{r.name}</option>)}</select><label className="sr-only" htmlFor="mechanism-filter">按机制筛选</label><select id="mechanism-filter" value={mechanism} onChange={(e) => setMechanism(e.target.value)}><option value="all">全部机制</option>{mechanisms.map((m) => <option key={m.slug} value={m.slug}>{m.name}</option>)}</select></div></div><div className="game-grid">{filtered.map((g) => <article className="game-card" key={g.slug} onClick={() => setActive(g)} tabIndex={0} onKeyDown={(e) => e.key === "Enter" && setActive(g)}><div className={`game-art ${g.accent}`}><span>{g.nativeName}</span><strong>{g.name[0]}</strong><i>✦</i></div><div className="game-info"><div className="game-top"><span>{countries.find((c) => g.countrySlugs.includes(c.slug))?.name}</span><span>{g.status === "published" ? mechanisms.find((m) => g.mechanismSlugs.includes(m.slug))?.name : "整理中"}</span></div><h3>{g.name}</h3><p>{g.blurb}</p><div className="meta"><span>◷ {g.duration}</span><span>♧ {g.players}</span><b>{g.status === "published" ? g.difficulty : "即将上线"}</b></div></div></article>)}</div></section>
    <footer><div className="brand"><span className="brand-mark">✦</span> WORLD CARD <small>ATLAS</small></div><p>探索世界纸牌文化，并立即开始游玩。</p><span>© 2026 World Card Atlas</span></footer>
    {active && <div className="modal-bg" role="presentation" onClick={() => setActive(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="game-dialog-title" onClick={(e) => e.stopPropagation()}><button className="close" aria-label="关闭详情" onClick={() => setActive(null)}>×</button><div className={`modal-art game-art ${active.accent}`}><span>{active.nativeName}</span><strong>{active.name[0]}</strong></div><p className="eyebrow">{countries.find((c) => active.countrySlugs.includes(c.slug))?.name}</p><h2 id="game-dialog-title">{active.name}</h2><p>{active.blurb}</p>{active.status === "published" ? <a className="btn primary" href={`/games/${active.slug}`}>查看完整档案 ↗</a> : <p className="status-note">内容整理中，即将上线。</p>}</div></div>}
  </main>;
}
